### ISSUE TITLE
Setup experiment tracking

### ISSUE THREAD

**Issue by rowandempster** [WATonomous/action-classification#6]
- [ ] Talk to @andy580 about metrics he added to the training pipeline last term
- [ ] Decide on an experiment tracking framework to use 
  - https://dvc.org/doc/start/experiments
  - https://wandb.ai/site
  - https://neptune.ai/experiment-tracking
  - https://www.mlflow.org/docs/latest/tracking.html
- [ ] Deploy tracking framework to the training pipeline
